// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oueujtveffxwcsjlaius.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91ZXVqdHZlZmZ4d2NzamxhaXVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NjAwMTcsImV4cCI6MjA3MzUzNjAxN30.i-k2RgCiiQq1cUpridsnj2lW9cXStsLCfhdtBejrEQ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});